---
stages:
- name: Build
  inputs:
  - url: https://github.com/sdevopsadm/spring-petclinic-microservices.git
    type: git
    branch: bluemix
    dir_name: null
  triggers:
  - type: commit
  jobs:
  - name: Package-api-gateway
    type: builder
    working_dir: spring-petclinic-api-gateway
    artifact_dir: target
    build_type: maven
    script: |
      #!/bin/bash

      export JAVA_HOME=$JAVA8_HOME
      mvn -B package
  - name: Package-api-gateway-nexus
    type: builder
    extension_id: ibm.devops.services.pipeline.maven.build.deploy
    SERVICE_INSTANCE: (default)
    WORKING_DIR: spring-petclinic-api-gateway
    ARCHIVE_DIR: target
    SONAR_SERVICE_INSTANCE: (default)
    BUILD_COMMAND: "#!/bin/bash\n# environment variables are available:\n# MAVEN_NAME:\
      \ name of the service instance\n# MAVEN_USER_ID: userid for the maven repository\n\
      # MAVEN_TOKEN: the token or password for the maven repository\n# MAVEN_SNAPSHOT_URL:\
      \ the maven snapshot repository\n# MAVEN_RELEASE_URL: the maven release repository\n\
      # MAVEN_MIRROR_URL: the maven mirror repository\n# SONAR_INSTANCE_NAME: the\
      \ name of the SonarQube instance\n# SONAR_SERVER_URL: the url of the SonarQube\
      \ server\n# SONAR_USER_ID: SonarQube user name\n# SONAR_USER_TOKEN: SonarQube\
      \ password or authentication token\n# The settings.xml is available in $HOME/.m2/settings.xml\n\
      # The name of the snapshots repository is 'snapshots'\n# The name of the release\
      \ repository is 'releases'\n# The name of the mirror repository is 'central'\n\
      \nexport JAVA_HOME=$JAVA8_HOME\ncd spring-petclinic-api-gateway\nmvn -DaltDeploymentRepository=central::default::${MAVEN_MIRROR_URL}\
      \ -B clean package \n#mvn -DaltDeploymentRepository=snapshots::default::${MAVEN_SNAPSHOT_URL}\
      \ deploy\n"
    SERVICE_INSTANCE_TYPE: nexus
- name: Test
  inputs:
  - type: job
    stage: Build
    job: Package-api-gateway
    dir_name: null
  triggers:
  - type: stage
  jobs:
  - name: Static Analystics
    type: tester
    script: |-
      #!/bin/bash

      CLASS=org.springframework.samples.petclinic
      TARGET=spring-petclinic-api-gateway-1.5.2.jar

      git clone https://github.com/jgkong/findbugs_extension.git

      export JAVA_HOME=$JAVA8_HOME
      export PATH=$JAVA_HOME/bin:$PATH

      export EXT_DIR=$(pwd)/findbugs_extension

      FINDBUGS_TGZ=$EXT_DIR/lib/findbugs-noUpdateChecks-3.0.1.tar.gz
      FINDBUGS_PREFIX='findbugs'
      FINDBUGS_XML='findbugs_report.xml'
      mkdir -p $FINDBUGS_PREFIX
      tar xz -C $FINDBUGS_PREFIX -f $FINDBUGS_TGZ
      FINDBUGS_DIR=$(pwd)/$(ls -d $FINDBUGS_PREFIX/findbugs*)

      $FINDBUGS_DIR/bin/findbugs -xml:withMessages -output $FINDBUGS_XML -onlyAnalyze ${CLASS}.- ${TARGET}
      mkdir -p tests
      python $EXT_DIR/findbug_to_junit.py $FINDBUGS_XML tests/TEST-findbugs.xml
    enable_tests: true
    test_file_pattern: tests/TEST-*.xml
- name: Deploy DEV to Bluemix CF
  inputs:
  - type: job
    stage: Build
    job: Package-api-gateway
    dir_name: null
  triggers:
  - type: stage
  jobs:
  - name: Deploy
    type: deployer
    target:
      region_id: ''
      organization: ''
      space: ''
      application: ''
    script: |
      #!/bin/bash
      cf push "${CF_APP}" -p spring-petclinic-api-gateway-1.5.2.jar
hooks:
- enabled: true
  label: null
  ssl_enabled: false
  url: https://devops-api.ng.bluemix.net/v1/messaging/webhook/publish
